# This file lists tools managed by Aftman, a toolchain manager for Roblox projects.
# For more information, see https://github.com/LPGhatguy/aftman

[tools]
tarmac = "Roblox/tarmac@0.7.0"
mantle = "blake-mealey/mantle@0.11.18"